export const GET_PLACES_REQUEST="GET_PLACES_REQUEST"
export const GET_PLACES_SUCCESS="GET_PLACES_SUCCESS"
export const GET_PLACES_FAILED="GET_PLACES_FAILED"

export const GET_TRANSPORT_REQUEST="GET_TRANSPORT_REQUEST"
export const GET_TRANSPORT_SUCCESS="GET_TRANSPORT_SUCCESS"
export const GET_TRANSPORT_FAILED="GET_TRANSPORT_FAILED"

export const GET_STAYS_REQUEST="GET_STAYS_REQUEST"
export const GET_STAYS_SUCCESS="GET_STAYS_SUCCESS"
export const GET_STAYS_FAILED="GET_STAYS_FAILED"

export const GET_POI_REQUEST="GET_POI_REQUEST"
export const GET_POI_SUCCESS="GET_POI_SUCCESS"
export const GET_POI_FAILED="GET_POI_FAILED"

export const GET_FOOD_REQUEST="GET_FOOD_REQUEST"
export const GET_FOOD_SUCCESS="GET_FOOD_SUCCESS"
export const GET_FOOD_FAILED="GET_FOOD_FAILED"







